# ---------------------------------------
# PostgreSQL – RDS (prod profile)
# ---------------------------------------

spring.datasource.url=jdbc:postgresql://cloudy-postgres.cd0kqosyqopb.eu-central-1.rds.amazonaws.com:5432/cloudydb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
